### ISSUE TITLE
Registration on local says "Incorrect, please try again."

### ISSUE THREAD

**Issue by bountyful** [bountyful/bountyfulcoins#2]
Running locally on MacOsx Mavericks.
Python tests run successfully

user name: humble
user email: up@up.com
password: happy

Entering captcha over 20 times, but unable to get to register success. No way to log errors and track where failure is happening.
runserver details are below:

```
[28/Feb/2014 19:03:28] "POST /register/ HTTP/1.1" 200 2327 (time: 0.44s; sql: 0ms (0q))
    [sql] SELECT ...
      FROM "auth_user"
      WHERE UPPER("auth_user"."username"::text) = UPPER(humble) LIMIT 1
    [sql] (1ms) Found 0 matching rows
    [sql] SELECT ...
      FROM "auth_user"
      WHERE UPPER("auth_user"."email"::text) = UPPER(up@up.com)
    [sql] (0ms) Found 0 matching rows
[28/Feb/2014 19:03:44] "POST /register/ HTTP/1.1" 200 2327 (time: 0.57s; sql: 0ms (0q))
```

**Comment by asfaltboy** [comment]
It seems recaptcha rejected the request without a proper private key. You'd need to provide one in your local settings file, for example:

### host_settings.py

```
from settings import *

#  get real key pair here: http://www.google.com/recaptcha/whyrecaptcha
RECAPTCHA_PUBLIC_KEY = 'THIS_SHOULD_BE_A_REAL_KEY'
RECAPTCHA_PRIVATE_KEY = 'THIS_SHOULD_BE_A_REAL_KEY'
```

 I'll elaborate in the deployment instructions.

**Comment by bountyful** [comment]
Acquiring keys for local testing and bountyfulcoins.com production.
