### ISSUE TITLE
Reply to Comment gives example page in production

### ISSUE THREAD

**Issue by bountyful** [bountyful/bountyfulcoins#7]
When Leaving a Comment in reply to another comment and clicking the "Add Comment" button, I get an example page.

**Comment by asfaltboy** [comment]
The built-in comment app relies on the Site host to be properly set.. by default the sites.Site model has one entry which is `example.com`.

Please set up the proper hostname in the sites admin. This is described in detail in [the sites docs](https://docs.djangoproject.com/en/1.6/ref/contrib/sites/#module-django.contrib.sites).

E.g: locally [i'd navigate here](http://localhost:8000/admin/sites/site/1/)

**Comment by bountyful** [comment]
Updated the sites domain and names. Closing.
