### ISSUE TITLE
ImportError: No module named bountyfulapp.models

### ISSUE THREAD

**Issue by bountyful** [bountyful/bountyfulcoins#9]
When setting up the crontab for decay:

  File "/var/www/bountyfulcoins.com/bountyfulcoins/bountyfulcoinsapp/management/commands/decay_balance.py", line 3, in <module>
    from bountyfulapp.models import Address
ImportError: No module named bountyfulapp.models

This should be bountyfulcoinsapp.models. Yes?

**Comment by asfaltboy** [comment]
You are right, my bad! I thought I added a test for that. I'll fix it
tomorrow

**Comment by bountyful** [comment]
Fixed in master. Test for tomorrow okay. Thanks.
